# -*- coding: utf-8 -*-
"""Week12_3D_MapLibre_Narikan.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18y-bxn2tT9Cz_eiqrK1Za99Hv0Jfxemr

# สัปดาห์ที่ 12: การสร้างแผนที่ 3 มิติ ด้วย MapLibre 🏔️
## GE 234 Basic Programming for Geographers
**วันที่:** 23 มีนาคม 2569
**ผศ.ดร.สิทธิศักดิ์ หมูคำหล้า**

---

### สิ่งที่จะได้เรียนรู้วันนี้
1. MapLibre คืออะไร และ 3D Web Map
2. การใช้ maplibregl ใน Python ด้วย leafmap
3. การสร้าง 3D Terrain Map
4. การ Extrude อาคาร (3D Buildings)
5. การเพิ่ม 3D Markers และ Popup
6. การสร้าง 3D Choropleth Map
7. การ Export แผนที่ 3 มิติ

## 1. MapLibre คืออะไร?

**MapLibre GL JS** เป็น Open-source library สำหรับสร้างแผนที่แบบ Vector ที่รองรับ 3D
เป็น Fork ของ Mapbox GL JS (เวอร์ชันเปิดเสรี)

### ข้อดีของ MapLibre
- แสดง 3D Terrain (ภูมิประเทศ 3 มิติ) ได้สวยงาม
- รองรับ Vector Tiles ทำให้ Zoom ได้ลื่นไหล
- Extrude อาคาร, ข้อมูลเป็น 3D ได้
- ใช้ WebGL สำหรับ rendering ที่เร็ว
- ใช้ฟรี ไม่มี API key (ต่างจาก Mapbox)

### การใช้งานใน Python
ใช้ผ่าน `leafmap` ที่มี module `leafmap.maplibregl`
"""

# ติดตั้ง dependencies
!pip install leafmap maplibre -q

"""## 2. สร้างแผนที่ 3D แรกของเรา

เริ่มจากแผนที่ MapLibre พื้นฐานพร้อม 3D Terrain
"""

import leafmap.maplibregl as leafmap

# สร้างแผนที่ 3D พื้นฐาน
m = leafmap.Map(
    center=[98.98, 18.79],  # เชียงใหม่ (lon, lat)
    zoom=10,
    pitch=60,    # มุมเอียง (0=มองตรง, 60=เอียง)
    bearing=30,  # มุมหมุน
    style="https://demotiles.maplibre.org/style.json"
)
m

"""## 3. การเพิ่ม 3D Terrain

ทำให้แผนที่แสดงภูมิประเทศเป็น 3 มิติ ด้วย Digital Elevation Model (DEM)
"""

# สร้างแผนที่พร้อม 3D Terrain
m = leafmap.Map(
    center=[98.98, 18.79],
    zoom=11,
    pitch=60,
    bearing=-20,
    style="https://basemaps.cartocdn.com/gl/positron-gl-style/style.json"
)

# เพิ่ม 3D Terrain จาก DEM
# Original error: AttributeError: 'Map' object has no attribute 'add_terrain'
# Fix: Use m.add_source and m.set_terrain directly.

# 1. Add the terrain source
terrain_source_url = "https://api.maptiler.com/tiles/terrain-rgb-v2/tiles.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL"
m.add_source("terrain_data", {
    "type": "raster-dem",
    "url": terrain_source_url,
    "tileSize": 256 # Adding tileSize as it's common for raster-dem sources
})

# 2. Set the terrain properties
m.set_terrain({
    "source": "terrain_data",
    "exaggeration": 1.5  # ขยายความสูง 1.5 เท่า
})

m

# ใช้ Terrain กับภาพดาวเทียมพื้นหลัง
m = leafmap.Map(
    center=[98.5, 19.0],  # ดอยอินทนนท์
    zoom=12,
    pitch=70,
    bearing=45,
    style={
        "version": 8,
        "sources": {
            "osm": {
                "type": "raster",
                "tiles": ["https://tile.openstreetmap.org/{z}/{x}/{y}.png"],
                "tileSize": 256,
                "attribution": "© OpenStreetMap"
            }
        },
        "layers": [{"id": "osm", "type": "raster", "source": "osm"}]
    }
)

# Fix: Use m.add_source and m.set_terrain directly.
terrain_source_url = "https://api.maptiler.com/tiles/terrain-rgb-v2/tiles.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL"
m.add_source("terrain_data", {
    "type": "raster-dem",
    "url": terrain_source_url,
    "tileSize": 256
})
m.set_terrain({
    "source": "terrain_data",
    "exaggeration": 2.0
})
m

"""## 4. 3D Buildings (การ Extrude อาคาร)

MapLibre สามารถแสดงอาคารเป็น 3 มิติจากข้อมูล OpenStreetMap
"""

# แสดง 3D Buildings
m = leafmap.Map(
    center=[100.52, 13.75],  # กรุงเทพ
    zoom=16,
    pitch=60,
    bearing=-17,
    style="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
)

# To add 3D buildings with custom styling, we need to add the source
# and then add a fill-extrusion layer explicitly.

# Add a vector source for building data. CartoDB's vector tiles often contain this.
# We'll use a common source ID and URL for this purpose.
building_source_id = "carto_buildings"
m.add_source(building_source_id, {
    "type": "vector",
    "url": "https://tiles.basemaps.cartocdn.com/vectortiles/carto.streets/v1/all.json",
    "promoteId": {"building": "id"} # Important for feature identification
})

# Define the 3D building layer with custom paint properties
building_layer = {
    "id": "3d-buildings-custom",
    "type": "fill-extrusion",
    "source": building_source_id, # Reference the source we just added
    "source-layer": "building", # The layer name within the vector tiles for buildings
    "filter": ["==", "extrude", "true"], # Filter to only extrude actual buildings
    "minzoom": 15, # Apply min_zoom here
    "paint": {
        "fill-extrusion-color": "#97BC62",
        "fill-extrusion-height": ["get", "height"],
        "fill-extrusion-base": ["get", "min_height"],
        "fill-extrusion-opacity": 0.7
    }
}

m.add_layer(building_layer)
m

"""## 5. 3D Choropleth Map

สร้างแผนที่แบบ Choropleth ที่ Extrude ความสูงตามค่าข้อมูล
"""

import json

# สร้างข้อมูลตัวอย่าง GeoJSON (สี่เหลี่ยมแทนเขต)
features = []
districts = [
    {"name": "บางกะปิ", "pop": 150000, "coords": [[100.60, 13.76], [100.63, 13.76], [100.63, 13.79], [100.60, 13.79], [100.60, 13.76]]},
    {"name": "ลาดพร้าว", "pop": 120000, "coords": [[100.57, 13.79], [100.60, 13.79], [100.60, 13.82], [100.57, 13.82], [100.57, 13.79]]},
    {"name": "วังทองหลาง", "pop": 100000, "coords": [[100.60, 13.79], [100.63, 13.79], [100.63, 13.82], [100.60, 13.82], [100.60, 13.79]]},
    {"name": "บึงกุ่ม", "pop": 160000, "coords": [[100.63, 13.79], [100.66, 13.79], [100.66, 13.82], [100.63, 13.82], [100.63, 13.79]]},
    {"name": "คันนายาว", "pop": 90000, "coords": [[100.63, 13.76], [100.66, 13.76], [100.66, 13.79], [100.63, 13.79], [100.63, 13.76]]},
]

for d in districts:
    features.append({
        "type": "Feature",
        "properties": {"name": d["name"], "population": d["pop"]},
        "geometry": {"type": "Polygon", "coordinates": [d["coords"]]}
    })

geojson = {"type": "FeatureCollection", "features": features}

print("ข้อมูลเขตตัวอย่าง:")
for d in districts:
    print(f"  {d['name']}: ประชากร {d['pop']:,} คน")

# สร้าง 3D Choropleth - ยิ่งประชากรมาก ยิ่งสูง
m = leafmap.Map(
    center=[100.62, 13.79],
    zoom=13,
    pitch=55,
    bearing=20,
    style="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
)

# เพิ่ม GeoJSON source
m.add_source("districts", {"type": "geojson", "data": geojson})

# เพิ่ม Fill Extrusion Layer
m.add_layer({
    "id": "districts-3d",
    "type": "fill-extrusion",
    "source": "districts",
    "paint": {
        "fill-extrusion-color": [
            "interpolate", ["linear"], ["get", "population"],
            80000, "#97BC62",   # น้อย = เขียวอ่อน
            120000, "#2C5F2D",  # กลาง = เขียวเข้ม
            160000, "#1A3A1C"   # มาก = เขียวเข้มมาก
        ],
        "fill-extrusion-height": [
            "interpolate", ["linear"], ["get", "population"],
            80000, 200,
            160000, 800
        ],
        "fill-extrusion-opacity": 0.8
    }
})

m

"""## 6. การเพิ่ม Marker บน 3D Map"""

# เพิ่ม Marker บนแผนที่ 3D
m = leafmap.Map(
    center=[100.52, 13.75],
    zoom=14,
    pitch=50,
    bearing=0,
    style="https://basemaps.cartocdn.com/gl/positron-gl-style/style.json"
)

# เพิ่ม markers
landmarks = [
    {"name": "วัดพระแก้ว", "lon": 100.4933, "lat": 13.7516},
    {"name": "วัดอรุณ", "lon": 100.4893, "lat": 13.7437},
    {"name": "วัดโพธิ์", "lon": 100.4930, "lat": 13.7468},
]

for lm in landmarks:
    # Fix: Wrap the popup string in a dictionary
    m.add_marker(lng_lat=[lm["lon"], lm["lat"]], popup={"message": lm["name"]})

m

"""## 7. การ Export แผนที่ 3D

สามารถ Export แผนที่ 3D เป็น HTML เพื่อแชร์ได้
"""

# สร้างแผนที่ 3D สวยๆ แล้ว Export
m = leafmap.Map(
    center=[98.98, 18.79],
    zoom=11,
    pitch=65,
    bearing=30,
    style="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
)


# Export
m.to_html("3d_map.html")
print("✅ บันทึกแผนที่ 3D เป็น 3d_map.html เรียบร้อย!")

"""## 🏋️ แบบฝึกหัด

### แบบฝึกหัดที่ 1
สร้างแผนที่ 3D Terrain ของบริเวณภาคเหนือของประเทศไทย ปรับมุมเอียง (pitch) และมุมหมุน (bearing) ให้ดูสวย

### แบบฝึกหัดที่ 2
สร้างแผนที่ 3D Buildings ของพื้นที่มหาวิทยาลัยธรรมศาสตร์ รังสิต ปรับสีอาคารตามต้องการ

### แบบฝึกหัดที่ 3
สร้าง 3D Choropleth Map จากข้อมูลจังหวัดที่คุณสนใจ (เช่น ประชากร, GDP, จำนวนนักท่องเที่ยว)

### แบบฝึกหัดที่ 4
สร้างแผนที่ 3D ที่ผสม Terrain + Markers ของสถานที่สำคัญ แล้ว Export เป็น HTML

แบบฝึกหัดที่ 1
สร้างแผนที่ 3D Terrain ของบริเวณภาคเหนือของประเทศไทย ปรับมุมเอียง (pitch) และมุมหมุน (bearing) ให้ดูสวย
"""

# สร้างแผนที่พร้อม 3D Terrain
m = leafmap.Map(
    center=[98.98, 18.79],
    zoom=11,
    pitch=60,
    bearing=-20,
    style="https://basemaps.cartocdn.com/gl/positron-gl-style/style.json"
)

# เพิ่ม 3D Terrain จาก DEM
# Original error: AttributeError: 'Map' object has no attribute 'add_terrain'
# Fix: Use m.add_source and m.set_terrain directly.

# 1. Add the terrain source
terrain_source_url = "https://api.maptiler.com/tiles/terrain-rgb-v2/tiles.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL"
m.add_source("terrain_data", {
    "type": "raster-dem",
    "url": terrain_source_url,
    "tileSize": 256 # Adding tileSize as it's common for raster-dem sources
})

# 2. Set the terrain properties
m.set_terrain({
    "source": "terrain_data",
    "exaggeration": 1.5  # ขยายความสูง 1.5 เท่า
})

m

"""แบบฝึกหัดที่ 2
สร้างแผนที่ 3D Buildings ของพื้นที่มหาวิทยาลัยธรรมศาสตร์ รังสิต ปรับสีอาคารตามต้องการ


"""

# แสดง 3D Buildings สำหรับมหาวิทยาลัยธรรมศาสตร์ รังสิต
import leafmap.maplibregl as leafmap

# กำหนดสีที่ต้องการสำหรับอาคาร
building_color = "#A9A9A9" # สีเทาเข้ม (DarkGray)

m = leafmap.Map(
    center=[100.6139, 14.0722],  # มหาวิทยาลัยธรรมศาสตร์ รังสิต
    zoom=16,
    pitch=60,
    bearing=-17,
    style="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
)

# To add 3D buildings with custom styling, we need to add the source
# and then add a fill-extrusion layer explicitly.

# Add a vector source for building data. CartoDB's vector tiles often contain this.
# We'll use a common source ID and URL for this purpose.
building_source_id = "carto_buildings"
m.add_source(building_source_id, {
    "type": "vector",
    "url": "https://tiles.basemaps.cartocdn.com/vectortiles/carto.streets/v1/all.json",
    "promoteId": {"building": "id"} # Important for feature identification
})

# Define the 3D building layer with custom paint properties
building_layer = {
    "id": "3d-buildings-custom",
    "type": "fill-extrusion",
    "source": building_source_id, # Reference the source we just added
    "source-layer": "building", # The layer name within the vector tiles for buildings
    "filter": ["==", "extrude", "true"], # Filter to only extrude actual buildings
    "minzoom": 15, # Apply min_zoom here
    "paint": {
        "fill-extrusion-color": building_color,
        "fill-extrusion-height": ["get", "height"],
        "fill-extrusion-base": ["get", "min_height"],
        "fill-extrusion-opacity": 0.7
    }
}

m.add_layer(building_layer)
m

"""แบบฝึกหัดที่ 3
สร้าง 3D Choropleth Map จากข้อมูลจังหวัดที่คุณสนใจ (เช่น ประชากร, GDP, จำนวนนักท่องเที่ยว)
"""

import json
import leafmap.maplibregl as leafmap

# สร้างข้อมูลตัวอย่าง GeoJSON สำหรับจังหวัดระยอง (อำเภอ) พร้อมข้อมูลประชากร
rayong_features = []
rayong_districts = [
    {"name": "เมืองระยอง", "pop": 250000, "coords": [[101.15, 12.65], [101.25, 12.65], [101.25, 12.75], [101.15, 12.75], [101.15, 12.65]]},
    {"name": "บ้านฉาง", "pop": 100000, "coords": [[101.00, 12.70], [101.10, 12.70], [101.10, 12.80], [101.00, 12.80], [101.00, 12.70]]},
    {"name": "แกลง", "pop": 80000, "coords": [[101.45, 12.60], [101.55, 12.60], [101.55, 12.70], [101.45, 12.70], [101.45, 12.60]]},
    {"name": "ปลวกแดง", "pop": 150000, "coords": [[101.10, 12.80], [101.20, 12.80], [101.20, 12.90], [101.10, 12.90], [101.10, 12.80]]},
    {"name": "วังจันทร์", "pop": 60000, "coords": [[101.50, 13.00], [101.60, 13.00], [101.60, 13.10], [101.50, 13.10], [101.50, 13.00]]},
    {"name": "บ้านค่าย", "pop": 110000, "coords": [[101.10, 12.50], [101.20, 12.50], [101.20, 12.60], [101.10, 12.60], [101.10, 12.50]]},
    {"name": "นิคมพัฒนา", "pop": 130000, "coords": [[101.25, 12.85], [101.35, 12.85], [101.35, 12.95], [101.25, 12.95], [101.25, 12.85]]},
    {"name": "เขาชะเมา", "pop": 40000, "coords": [[101.70, 12.90], [101.80, 12.90], [101.80, 13.00], [101.70, 13.00], [101.70, 12.90]]}
]

for d in rayong_districts:
    rayong_features.append({
        "type": "Feature",
        "properties": {"name": d["name"], "population": d["pop"]},
        "geometry": {"type": "Polygon", "coordinates": [d["coords"]]}
    })

rayong_geojson = {"type": "FeatureCollection", "features": rayong_features}

print("ข้อมูลอำเภอตัวอย่างในระยอง:")
for d in rayong_districts:
    print(f"  {d['name']}: ประชากร {d['pop']:,} คน")

# สร้าง 3D Choropleth - ยิ่งประชากรมาก ยิ่งสูง
m = leafmap.Map(
    center=[101.2, 12.75], # จุดศูนย์กลางสำหรับระยอง
    zoom=9,
    pitch=55,
    bearing=20,
    style="https://basemaps.cartocdn.com/gl/dark-matter-gl-style/style.json"
)

# เพิ่ม GeoJSON source
m.add_source("rayong_districts", {"type": "geojson", "data": rayong_geojson})

# เพิ่ม Fill Extrusion Layer
m.add_layer({
    "id": "rayong-districts-3d",
    "type": "fill-extrusion",
    "source": "rayong_districts",
    "paint": {
        "fill-extrusion-color": [
            "interpolate", ["linear"], ["get", "population"],
            40000, "#fef0d9",   # น้อย = สีอ่อน
            100000, "#fc8d59",  # กลาง = สีกลาง
            250000, "#d7301f"   # มาก = สีเข้ม
        ],
        "fill-extrusion-height": [
            "interpolate", ["linear"], ["get", "population"],
            40000, 100,
            250000, 1200
        ],
        "fill-extrusion-opacity": 0.8
    }
})

m

"""แบบฝึกหัดที่ 4
สร้างแผนที่ 3D ที่ผสม Terrain + Markers ของสถานที่สำคัญ แล้ว Export เป็น HTML
"""

import leafmap.maplibregl as leafmap

# 1. สร้างแผนที่ 3D พื้นฐานสำหรับภาคกลาง/กรุงเทพฯ
m = leafmap.Map(
    center=[100.49, 13.75],
    zoom=14,
    pitch=60,    # มุมเอียง
    bearing=30,  # มุมหมุน
    style="https://basemaps.cartocdn.com/gl/positron-gl-style/style.json"
)

# 2. เพิ่ม 3D Terrain จาก DEM
terrain_source_url = "https://api.maptiler.com/tiles/terrain-rgb-v2/tiles.json?key=get_your_own_OpIi9ZULNHzrESv6T2vL"
m.add_source("terrain_data", {
    "type": "raster-dem",
    "url": terrain_source_url,
    "tileSize": 256
})
m.set_terrain({
    "source": "terrain_data",
    "exaggeration": 1.5
})

# 3. เพิ่ม markers สถานที่สำคัญ
landmarks = [
    {"name": "วัดพระแก้ว", "lon": 100.4933, "lat": 13.7516},
    {"name": "วัดอรุณ", "lon": 100.4893, "lat": 13.7437},
    {"name": "วัดโพธิ์", "lon": 100.4930, "lat": 13.7468},
    {"name": "ภูเขาทอง", "lon": 100.505, "lat": 13.755}
]

for lm in landmarks:
    m.add_marker(lng_lat=[lm["lon"], lm["lat"]], popup={"message": lm["name"]})

# 4. Export แผนที่ 3 มิติ เป็น HTML
output_filename = "3d_terrain_markers_map.html"
m.to_html(output_filename)
print(f"✅ บันทึกแผนที่ 3D ที่มี Terrain และ Markers เป็น {output_filename} เรียบร้อย!")

m

"""---
### 📌 สัปดาห์หน้า
**สัปดาห์ที่ 13-16:** โครงการสุดท้าย - การนำเสนอแนวคิด

### 📋 งานที่ต้องส่ง
**Code Repository #4** - รวมโค้ดที่เขียนในคลาสวันนี้

---
*ภาควิชาภูมิศาสตร์ คณะศิลปศาสตร์ มหาวิทยาลัยธรรมศาสตร์*
"""